apiVersion: batch/v1
kind: Job

metadata:
  name: seedjob
spec:
  template:
    spec:
      containers:
      - name: seedjob
        image: 'nyuappsec/assign3-db:v0'
        command: ["/bin/sh"]
        args: ["-c","mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --database=${MYSQL_DATABASE} --host=mysql-service -f < /docker-entrypoint-initdb.d/seedjob.sql"]
        #adding arguments to trigger the SQL job to insert rows along with password and usernmae passed from secrets already stored
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: securedsecrets
                key: password

          - name:  MYSQL_DATABASE
            value: GiftcardSiteDB
            
      restartPolicy: Never
  backoffLimit: 7